apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowrootuser
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowRootUser
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisallowrootuser

        import rego.v1

        pod_spec := input.review.object.spec if {
          input.review.kind.kind == "Pod"
        }

        pod_spec := input.review.object.spec.template.spec if {
          input.review.object.spec.template.spec
        }

        containers contains container if {
          container := pod_spec.containers[_]
        }

        containers contains container if {
          container := pod_spec.initContainers[_]
        }

        violation contains {"msg": msg} if {
          pod_spec.securityContext.runAsUser == 0
          msg := "pod securityContext must not set runAsUser: 0"
        }

        violation contains {"msg": msg} if {
          container := containers[_]
          container.securityContext.runAsUser == 0
          msg := sprintf("container <%s> must not set runAsUser: 0", [container.name])
        }