apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlimits
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLimits
      validation:
        openAPIV3Schema:
          type: object
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlimits

        pod_spec = spec {
          input.review.kind.kind == "Pod"
          spec := input.review.object.spec
        }

        pod_spec = spec {
          spec := input.review.object.spec.template.spec
        }

        containers[container] {
          container := pod_spec.containers[_]
        }

        containers[container] {
          container := pod_spec.initContainers[_]
        }

        violation[{"msg": msg}] {
          container := containers[_]
          not container.resources.limits
          msg := sprintf("container <%s> must define resources.limits", [container.name])
        }

        violation[{"msg": msg}] {
          container := containers[_]
          container.resources.limits
          count(container.resources.limits) == 0
          msg := sprintf("container <%s> must define non-empty resources.limits", [container.name])
        }
