apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-dev-sa
  namespace: payments-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payments-dev-role
  namespace: payments-dev
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["argoproj.io"]
    resources:
      - rollouts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
