apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-templates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default

  source:
    repoURL: https://github.com/VietSory/temp.git
    targetRevision: main
    path: gatekeeper/templates

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=truec