apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    repoURL: https://sigstore.github.io/helm-charts
    chart: policy-controller
    targetRevision: 0.10.6
    helm:
      values: |
        installCRDs: true
        webhook:
          replicaCount: 1
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: policy.sigstore.dev
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        - .webhooks[]?.failurePolicy
        - .webhooks[]?.timeoutSeconds
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: policy.sigstore.dev
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        - .webhooks[]?.failurePolicy
        - .webhooks[]?.timeoutSeconds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
