apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  namespace: demo
spec:
  provider:
    fake:
      data:
        - key: demo/db/password
          value: "initial-password-v1"
